apiVersion: apps/v1
kind: Deployment
metadata:
  name: trip-planner-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: trip-planner
  replicas: 2
  template:
    metadata:
      labels:
        app: trip-planner
    spec:
      containers:
        - name: trip-planner
          image: trip-planner # Replace with your actual Docker image for the Flutter web app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # Typically, Flutter web apps run on port 80
apiVersion: v1
kind: Service
metadata:
  name: trip-planner-service
  namespace: default
spec:
  selector:
    app: trip-planner
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: NodePort
