apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: flutter-web-k8s-deployment
  namespace: default
spec:
  selector:
    matchLabels:
      app: flutter-web-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: flutter-web-k8s
    spec:
      containers:
        - name: flutter-web-k8s
          image: trip_planner # Image that will be used to containers in the cluster
          imagePullPolicy: Always
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
      imagePullSecrets:
        - name: regcred


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: flutter-web-k8ssvc
  namespace: default
spec:
  selector:
    app: flutter-web-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.